image:
  repository: quay.io/fernando_taboada/hp_asm
  tag: 3.8.0-1869.4
  pullPolicy: IfNotPresent

serviceAccount:
  name: hp-ams-sa

daemonSet:
  name: hp-ams-installer
  namespace: default
  privileged: true
  volumePath: /

rbac:
  enabled: true

autoscaling:
  enabled: false

nodeSelector:
  kubernetes.io/hostname: "workernode01" 