{{- if not (lookup "v1" "ServiceAccount" .Release.Namespace .Values.serviceAccount.name) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{- end }}
